// Code generated by protoc-gen-go.
// source: skynet.proto
// DO NOT EDIT!

package skynet

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type SInt32 struct {
	Value            *int32 `protobuf:"zigzag32,1,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *SInt32) Reset()         { *this = SInt32{} }
func (this *SInt32) String() string { return proto.CompactTextString(this) }
func (*SInt32) ProtoMessage()       {}

func (this *SInt32) GetValue() int32 {
	if this != nil && this.Value != nil {
		return *this.Value
	}
	return 0
}

type SInt64 struct {
	Value            *int64 `protobuf:"zigzag64,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *SInt64) Reset()         { *this = SInt64{} }
func (this *SInt64) String() string { return proto.CompactTextString(this) }
func (*SInt64) ProtoMessage()       {}

func (this *SInt64) GetValue() int64 {
	if this != nil && this.Value != nil {
		return *this.Value
	}
	return 0
}

func init() {
}
