// Code generated by protoc-gen-go.
// source: skynet.proto
// DO NOT EDIT!

/*
Package skynet is a generated protocol buffer package.

It is generated from these files:
	skynet.proto

It has these top-level messages:
	Psint32
	Psint64
	Pstring
	AppServer
	AppMsg
*/
package skynet

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type SkynetMsg int32

const (
	SkynetMsg_SM_APP_INFO          SkynetMsg = 0
	SkynetMsg_SM_APP_DISCONNECTED  SkynetMsg = 1
	SkynetMsg_SM_SEND_TO_APP       SkynetMsg = 16
	SkynetMsg_SM_AGENT_EXECUTE_CMD SkynetMsg = 32
	SkynetMsg_SM_AGENT_FIND_APPS   SkynetMsg = 33
)

var SkynetMsg_name = map[int32]string{
	0:  "SM_APP_INFO",
	1:  "SM_APP_DISCONNECTED",
	16: "SM_SEND_TO_APP",
	32: "SM_AGENT_EXECUTE_CMD",
	33: "SM_AGENT_FIND_APPS",
}
var SkynetMsg_value = map[string]int32{
	"SM_APP_INFO":          0,
	"SM_APP_DISCONNECTED":  1,
	"SM_SEND_TO_APP":       16,
	"SM_AGENT_EXECUTE_CMD": 32,
	"SM_AGENT_FIND_APPS":   33,
}

func (x SkynetMsg) Enum() *SkynetMsg {
	p := new(SkynetMsg)
	*p = x
	return p
}
func (x SkynetMsg) String() string {
	return proto.EnumName(SkynetMsg_name, int32(x))
}
func (x *SkynetMsg) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SkynetMsg_value, data, "SkynetMsg")
	if err != nil {
		return err
	}
	*x = SkynetMsg(value)
	return nil
}

type Psint32 struct {
	Value            *int32 `protobuf:"zigzag32,1,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Psint32) Reset()         { *m = Psint32{} }
func (m *Psint32) String() string { return proto.CompactTextString(m) }
func (*Psint32) ProtoMessage()    {}

func (m *Psint32) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type Psint64 struct {
	Value            *int64 `protobuf:"zigzag64,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Psint64) Reset()         { *m = Psint64{} }
func (m *Psint64) String() string { return proto.CompactTextString(m) }
func (*Psint64) ProtoMessage()    {}

func (m *Psint64) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type Pstring struct {
	Value            *string `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Pstring) Reset()         { *m = Pstring{} }
func (m *Pstring) String() string { return proto.CompactTextString(m) }
func (*Pstring) ProtoMessage()    {}

func (m *Pstring) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type AppServer struct {
	Id               *string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Host             *string `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
	Port             *uint32 `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AppServer) Reset()         { *m = AppServer{} }
func (m *AppServer) String() string { return proto.CompactTextString(m) }
func (*AppServer) ProtoMessage()    {}

func (m *AppServer) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *AppServer) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *AppServer) GetPort() uint32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

type AppMsg struct {
	AppId            *string `protobuf:"bytes,1,req,name=app_id" json:"app_id,omitempty"`
	Head             *uint32 `protobuf:"varint,2,req,name=head" json:"head,omitempty"`
	Data             []byte  `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	FromApp          *string `protobuf:"bytes,4,opt,name=from_app" json:"from_app,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AppMsg) Reset()         { *m = AppMsg{} }
func (m *AppMsg) String() string { return proto.CompactTextString(m) }
func (*AppMsg) ProtoMessage()    {}

func (m *AppMsg) GetAppId() string {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return ""
}

func (m *AppMsg) GetHead() uint32 {
	if m != nil && m.Head != nil {
		return *m.Head
	}
	return 0
}

func (m *AppMsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AppMsg) GetFromApp() string {
	if m != nil && m.FromApp != nil {
		return *m.FromApp
	}
	return ""
}

func init() {
	proto.RegisterEnum("skynet.SkynetMsg", SkynetMsg_name, SkynetMsg_value)
}
